window.DASHBOARD_CONFIG = {
  DATA_URL: "https://script.google.com/macros/s/AKfycbwWaEjc8uPEAFeWbyoUv_rZ1KZ5Neulg6qoPVsL90hGnh-SLLPVxIkJMJ0kdwPcLKM/exec",

  DEFAULT_ROTATION_SECONDS: 60,
  DEFAULT_REFRESH_SECONDS: 300,
  DEFAULT_TRIGGER_REFRESH_SECONDS: 10,
  DEFAULT_TRIGGER_DISPLAY_SECONDS: 45,

  ENABLE_AUTO_REFRESH: true,
  ENABLE_TRIGGER_INTERRUPTIONS: true,

  TEAMS_TO_SHOW: ["NOVA", "VF", "MHM"]
};
